P010Store.WebUI/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using P010Store.Entities;
using P010Store.Service.Abstract;
using P010Store.WebUI.Utils;

namespace P010Store.WebUI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Policy = "AdminPolicy")]
    public class ProductsController : Controller
    {
        private readonly IService<Product> _service;
        private readonly IService<Category> _serviceCategory;
        private readonly IService<Brand> _serviceBrand;
        private readonly IProductService _productService;
        public ProductsController(IService<Product> service, IService<Category> serviceCategory, IService<Brand> serviceBrand, IProductService productService)
        {
            _service = service;
            _serviceCategory = serviceCategory;
            _serviceBrand = serviceBrand;
            _productService = productService; //InvalidOperationException: Unable to resolve service for type 'P010Store.Service.Abstract.IProductService' while attempting to activate 'P010Store.WebUI.Areas.Admin.Controllers.ProductsController'.  bu servisi kullandığımızda bu hatayı alırız, bu sorunu çözmek için servisi program.cs de tanımlamamız gerekir.

        }
        // GET: ProductsController
        public async Task<ActionResult> IndexAsync()
        {
            var model = await _productService.GetAllProductsByCategoriesBrandsAsync();//eskisi _service.GetAll();
            return View(model);
        }

        // GET: ProductsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductsController/Create
        public async Task<ActionResult> CreateAsync()
        {
            ViewBag.CategoryId = new SelectList(await _serviceCategory.GetAllAsync(), "Id","Name");
            ViewBag.BrandId = new SelectList(await _serviceBrand.GetAllAsync(), "Id", "Name");
            return View();
        }

        // POST: ProductsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(Product product, IFormFile? Image)
        {
            try
            {
                if (Image is not null) product.Image = await FileHelper.FileLoaderAsync(Image, filePath: "/wwwroot/Img/Products/");
                await _service.AddAsync(product);
                await _service.SaveChangesAsync();
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                ModelState.AddModelError("", "Hata Oluştu!");
            }

            ViewBag.CategoryId = new SelectList(await _serviceCategory.GetAllAsync(), "Id", "Name"); //burada ürün ekleme esnasında ekleme başarısız olursa ekrandaki select elementlerine verileri tekrar gönderiyoruz aksi taktirde null reference hatası alırız.
            ViewBag.BrandId = new SelectList(await _serviceBrand.GetAllAsync(), "Id", "Name");
            
            return View(product);
    }

        // GET: ProductsController/Edit/5
        public async Task<ActionResult> EditAsync(int id)
        {
            var model = await _service.FindAsync(id);
            return View(model);
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(int id, Product product, IFormFile? Image, bool? resmisil)
        {
            try
            {
                if (resmisil == true)
                {
                    FileHelper.FileRemover(product.Image);
                    product.Image = string.Empty;
                }
                if (Image is not null) product.Image = await FileHelper.FileLoaderAsync(Image, filePath: "/wwwroot/Img/Products/");
                _service.Update(product);
                await _service.SaveChangesAsync();
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                ModelState.AddModelError("", "Hata Oluştu!");
            }

            ViewBag.CategoryId = new SelectList(await _serviceCategory.GetAllAsync(), "Id", "Name");
            ViewBag.BrandId = new SelectList(await _serviceBrand.GetAllAsync(), "Id", "Name");

            return View(product);
        }

        // GET: ProductsController/Delete/5
        public async Task<ActionResult> DeleteAsync(int id)
        {
            var model = await _service.FindAsync(id);
            return View(model);
        }

        // POST: ProductsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id,Product product)
        {
            try
            {
                FileHelper.FileRemover(product.Image);
                _service.Delete(product);
                _service.SaveChanges();
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }
    }
}

P010Store.WebUI/Controllers/BrandsController.cs
using Microsoft.AspNetCore.Mvc;
using P010Store.Entities;
using P010Store.Service.Abstract;
using P010Store.WebUI.Models;

namespace P010Store.WebUI.Controllers
{
    public class BrandsController : Controller
    {
        private readonly IService<Brand> _serviceBrand;
        private readonly IService<Product>  _service;

        public BrandsController(IService<Brand> serviceBrand, IService<Product> service)
        {
            _serviceBrand = serviceBrand;
            _service = service;
        }

        public async Task<IActionResult> IndexAsync(int id)
        {
            var model = new BrandPageViewModel()
            {
                Brand =await _serviceBrand.FindAsync(id),
                Products= await _service.GetAllAsync(p=>p.IsActive && p.BrandId
                ==id)
            };
            return View(model);
        }
    }
}

P010Store.WebUI/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using P010Store.Service.Abstract;

namespace P010Store.WebUI.Controllers
{
	public class CategoriesController : Controller
	{
        private readonly ICategoryService _service;

        public CategoriesController(ICategoryService service)
        {
            _service = service;
        }

        public async Task<IActionResult> IndexAsync(int id)
		{
            var model = await _service.GetCategoryByProducts(id);
			return View(model);
		}
	}
}

P010Store.WebUI/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using P010Store.Entities;
using P010Store.Service.Abstract;
using P010Store.WebUI.Models;
using System.Net.Http;

namespace P010Store.WebUI.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _service;

        public ProductsController(IProductService service)
        {
            _service = service;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var model = await _service.GetAllAsync(p => p.IsActive);
            return View(model);
        }

        public async Task<IActionResult> Search(string q)
        {
            var model = await _service.GetAllAsync(p => p.IsActive && p.Name.Contains(q));
            return View(model);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var product = await _service.GetProductByCategoriesBrandsAsync(id);
            var model = new ProductDetailViewModel()
            {
                Product = product,
                Products = await _service.GetAllAsync(p => p.CategoryId == product.CategoryId && p.Id != id)
            };

            return View(model);
        }
    }
}

P010Store.WebUI/Areas/Admin/Views/Products/Create.cshtml
@model Product

@{
    ViewData["Title"] = "Ürün Ekle";
}


<h1>Ürün Ekle</h1>

<h4>Ürün Bilgileri</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsHome" /> @Html.DisplayNameFor(model => model.IsHome)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <div class="d-flex">
                    <select asp-for="CategoryId" class="form-select" asp-items="ViewBag.CategoryId"></select>
                    <button type="button" onclick="kEkle()" class="btn btn-outline-success col-md-1">+</button>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <div class="d-flex">
                    <select asp-for="BrandId" class="form-select" asp-items="ViewBag.BrandId"></select>
                    <button type="button" onclick="bEkle()" value="+" class="btn btn-outline-success col-md-1">+</button>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Dön</a>
</div>

<div class="modal fade bd-example-modal-lg" id="kategoriModal" tabindex="-1" role="dialog" aria-labelledby="myModal" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-autoheight" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myNodal">Kategori Ekle</h5>
            </div>
            <div class="modal-body">
                <form asp-action="Create2" asp-controller="Categories" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group my-2">
                        <label class="control-label">Kategori Adı</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group my-2">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group my-2">
                        <label asp-for="Image" class="control-label"></label>
                        <input asp-for="Image" class="form-control" type="file" />
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check my-2">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                        </label>
                    </div>
                    <div class="form-group my-2">
                        <input type="submit" value="Ekle" class="btn btn-primary col-12" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-lg" id="markaModal" tabindex="-1" role="dialog" aria-labelledby="myModal2" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-autoheight" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModal2">Marka Ekle</h5>
            </div>
            <div class="modal-body">
                <form asp-action="Create2" asp-controller="Brands" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group my-2">
                        <label class="control-label">Marka Adı</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group my-2">
                        <label class="control-label">Marka Açıklaması</label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group form-check my2">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                        </label>
                    </div>
                    <div class="form-group my-2">
                        <input type="submit" value="Ekle" class="btn btn-primary col-12" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script>
        function kEkle() {
            var myModal = new bootstrap.Modal(document.getElementById("kategoriModal"));
            myModal.show();
        };
        function bEkle() {
            var myModal2 = new bootstrap.Modal(document.getElementById("markaModal"));
            myModal2.show();
        };
    </script>
}

P010Store.WebUI/Areas/Admin/Views/Products/Delete.cshtml
@model P010Store.Entities.Product

@{
    ViewData["Title"] = "Sil";
}

<h1>Sil</h1>

<h3>Silmek istiyor musunuz?</h3>
<div>
    <h4>Ürün</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsHome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsHome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Image" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a asp-action="Index">Listeye Dön</a>
    </form>
</div>

P010Store.WebUI/Areas/Admin/Views/Products/Edit.cshtml
@model P010Store.Entities.Product

@{
    ViewData["Title"] = "Ürün Düzenle";
}


<h1>Ürün Düzenle</h1>

<h4>Ürün Bilgileri</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Image" />
            <input type="hidden" asp-for="CreateDate" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" />
                <span asp-validation-for="Image" class="text-danger"></span>

                @if (!string.IsNullOrWhiteSpace(Model.Image))
                {
                    <label class="my-3">
                        <a href="/Img/Products/@Model.Image" data-toggle="lightbox">
                            <img src="/Img/Products/@Model.Image" alt="@Model.Image" title="@Model.Image" height="50" />
                        </a>
                        @Html.CheckBox("resmiSil") Resmi Sil
                    </label>
                }

            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsHome" /> @Html.DisplayNameFor(model => model.IsHome)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-select" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-select" asp-items="ViewBag.BrandId"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group my-3">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Dön</a>
</div>

@section Scripts{
    <script>
        $(document).on('click', '[data-toggle="lightbox"]', function (event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });
    </script>
}

P010Store.WebUI/Areas/Admin/Views/Products/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Ürünler";
}

<h1>Ürünler</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Yeni Ekle</a>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsHome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                <img src="/Img/Products/@item.Image" alt="" height="40"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsHome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
            <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Düzenle</a> |

                    <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
            </td>
        </tr>
}
    </tbody>
</table>